language: node_js
node_js:
  - "9"
script: 
- "npm test"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main

# blocklist
branches:
  except:
    - HerokuTesting
